In [2]:
import numpy as np

# Define the mean vector and covariance matrix

def generate_mvn(μ_γ, Σ_γ, size=1):
    
    if μ_γ is None:
        μ_γ = np.array([0, 0]) 
    
    if Σ_γ is None:
        Σ_γ = np.array([[1, 0], [0, 1]])

    # Generate random samples from the multivariate normal distribution
    mvn_sample = np.random.multivariate_normal(μ_γ, Σ_γ, size=size)
    
    return mvn_sample

# Print the generated sam

generate_mvn()


array([[-0.98966992,  0.97315006]])

In [7]:
import numpy as np
from scipy.stats import wishart

# Define the mean vector and covariance matrix

def generate_wishart(Φ_w=None, df=None, size=1):
    if Φ_w is None:
        Φ_w = np.array([[1, 0], [0, 1]])


    # Define the degrees of freedom
    if df is None:
        df = 3

    # Generate random samples from the Wishart distribution
    wishart_samples = wishart.rvs(df, Φ_w, size=1)

    # Print the generated samples
    return wishart_samples

generate_wishart()

array([[0.78590475, 0.98960179],
       [0.98960179, 3.6605202 ]])

In [16]:
import numpy as np

def create_block_matrix(mat, vec):
    # Create the block matrix
    block_matrix = np.block([[mat, vec[:, np.newaxis]], [vec, 1]])

    # Return the block matrix
    return block_matrix

# Define the matrix and vector
mat = np.array([[1, 2], [3, 4]])
vec = np.array([5, 6])

# Call the create_block_matrix function
block_matrix = create_block_matrix(mat, vec)

# Print the block matrix
print(block_matrix)


[[1 2 5]
 [3 4 6]
 [5 6 1]]


In [9]:

# Define the matrix and vecto

# def create_block_matrix(mat, vec):
#     # Create the block matrix
#     block_matrix = np.block([[mat, vec[:, np.newaxis]], [vec, 1]])

#     # Print the block matrix
#     return block_matrix

In [10]:
import numpy as np

# Define the matrix

def calculate_log_det(matrix):

    # Calculate the determinant of the matrix
    det = np.linalg.det(matrix)
    # Calculate the log of the determinant of the matrix
    log_det = np.log(det)

    # Print the log of the determinant of the matrix
    return log_det


In [34]:
def sample_pipeline(num_samples=20):
    det_samples = []
    for _ in range(num_samples):
        mvn_sample = generate_mvn()[0]
        wish_sample = generate_wishart()[0]
        mvn_sample= mvn_sample.T # print(mvn_sample.T.shape)
        print(wish_sample.shape)
        #assert 0 == 1
        block_mat = create_block_matrix(wish_sample, mvn_sample.T)
        log_det = calculate_log_det(block_mat)
        det_samples.append(log_det)
    
    return det_samples
    

In [35]:
import matplotlib.pyplot as plt

# Run the sample pipeline
det_samples = sample_pipeline()

# Plot the samples
plt.plot(det_samples)
plt.xlabel('Sample Index')
plt.ylabel('Log Determinant')
plt.title('Log Determinant Samples')
plt.show()


(2,)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2